/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 ../../public/model/model.glb -o ../../public/model/model-jsx.jsx -t -k -d -T
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Water: THREE.Mesh;
        Terrain_remesh: THREE.Mesh;
        Cylinder: THREE.Mesh;
        Sand: THREE.Mesh;
        Cross: THREE.Mesh;
        Cube7: THREE.Mesh;
        Sand6: THREE.Mesh;
        Sand3: THREE.Mesh;
        Cube4_0: THREE.Mesh;
        Cross1: THREE.Mesh;
        Pool: THREE.Mesh;
        Sand_1: THREE.Mesh;
        Sand_2: THREE.Mesh;
    };
    materials: {
        WAter: THREE.MeshStandardMaterial;
        ['Mat.2']: THREE.MeshStandardMaterial;
        Sand: THREE.MeshStandardMaterial;
        WhiteLine: THREE.MeshStandardMaterial;
        Wood: THREE.MeshStandardMaterial;
        PoolColor: THREE.MeshStandardMaterial;
        Grass: THREE.MeshStandardMaterial;
        CourtColor: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/model/model-transformed.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <PerspectiveCamera
                name="Morph"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[7.18, 6.2, 9.21]}
                rotation={[-0.59, 0.6, 0.36]}
            />
            <PerspectiveCamera
                name="3"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={32.27}
                position={[4.12, 0.26, 1.2]}
                rotation={[-0.15, 1.24, 0.14]}
            />
            <PerspectiveCamera
                name="2"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[7.18, 6.2, 9.21]}
                rotation={[-0.59, 0.6, 0.36]}
            />
            <PerspectiveCamera
                name="1"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[-2.73, 1.28, 15.07]}
                rotation={[0.05, -0.26, 0.01]}
            />
            <mesh name="Water" geometry={nodes.Water.geometry} material={materials.WAter} position={[0, -0.03, 0]} />
            <mesh name="Terrain_remesh" geometry={nodes.Terrain_remesh.geometry} material={materials['Mat.2']} />
            <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
                position={[-0.61, 0.04, 0.23]}
                rotation={[0, Math.PI / 9, 0]}
            />
            <mesh
                name="Sand"
                geometry={nodes.Sand.geometry}
                material={materials.Sand}
                position={[0.04, 0, -0.96]}
                rotation={[0, -0.44, 0]}
            />
            <mesh
                name="Cross"
                geometry={nodes.Cross.geometry}
                material={materials.WhiteLine}
                position={[-0.58, 0, -1.18]}
                rotation={[0, -0.43, 0]}
            />
            <mesh
                name="Cube7"
                geometry={nodes.Cube7.geometry}
                material={materials.Wood}
                position={[-2.01, 0.04, 0.29]}
                rotation={[0, -0.56, 0]}
            />
            <mesh name="Sand6" geometry={nodes.Sand6.geometry} material={materials.WhiteLine} />
            <mesh name="Sand3" geometry={nodes.Sand3.geometry} material={materials.WhiteLine} />
            <mesh name="Cube4_0" geometry={nodes.Cube4_0.geometry} material={nodes.Cube4_0.material} />
            <mesh name="Cross1" geometry={nodes.Cross1.geometry} material={materials.WhiteLine} />
            <mesh
                name="Pool"
                geometry={nodes.Pool.geometry}
                material={materials.PoolColor}
                position={[-3, -0.04, -0.57]}
                rotation={[0, 0.04, 0]}
            />
            <mesh
                name="Sand_1"
                geometry={nodes.Sand_1.geometry}
                material={materials.Grass}
                position={[0.46, 0, -0.77]}
                rotation={[0, -0.44, 0]}
            />
            <mesh
                name="Sand_2"
                geometry={nodes.Sand_2.geometry}
                material={materials.CourtColor}
                position={[0.2, 0, -0.88]}
                rotation={[0, -0.44, 0]}
            />
        </group>
    );
}

useGLTF.preload('/model-transformed.glb');
