/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 ../../public/model/model.glb -o ../../public/model/model-jsx.jsx -t -k -d -T
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Water: THREE.Mesh;
        Terrain_remesh: THREE.Mesh;
        Cylinder: THREE.Mesh;
        Sand: THREE.Mesh;
        Cross: THREE.Mesh;
        Cube7: THREE.Mesh;
        Sand6: THREE.Mesh;
        Sand3: THREE.Mesh;
        Cube4_0: THREE.Mesh;
        Cross1: THREE.Mesh;
        Pool: THREE.Mesh;
        Sand_1: THREE.Mesh;
        Sand_2: THREE.Mesh;
    };
    materials: {
        WAter: THREE.MeshStandardMaterial;
        ['Mat.2']: THREE.MeshStandardMaterial;
        Sand: THREE.MeshStandardMaterial;
        WhiteLine: THREE.MeshStandardMaterial;
        Wood: THREE.MeshStandardMaterial;
        PoolColor: THREE.MeshStandardMaterial;
        Grass: THREE.MeshStandardMaterial;
        CourtColor: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/model/model-transformed.glb') as GLTFResult;

    return (
        <group {...props} dispose={null}>
            <PerspectiveCamera
                name="Morph"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[7.18, 6.2, 9.21]}
                rotation={[-0.59, 0.6, 0.36]}
            />
            <PerspectiveCamera
                name="3"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={32.27}
                position={[4.12, 0.26, 1.2]}
                rotation={[-0.15, 1.24, 0.14]}
            />
            <PerspectiveCamera
                name="2"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[7.18, 6.2, 9.21]}
                rotation={[-0.59, 0.6, 0.36]}
            />
            <PerspectiveCamera
                name="1"
                makeDefault={false}
                far={10000000000}
                near={0.01}
                fov={12.84}
                position={[-2.73, 1.28, 15.07]}
                rotation={[0.05, -0.26, 0.01]}
            />
            <mesh
                name="Water"
                geometry={nodes.Water.geometry}
                material={
                    new THREE.ShaderMaterial({
                        uniforms: THREE.UniformsUtils.merge([
                            THREE.UniformsLib['fog'],
                            {
                                normalSampler: { type: 't', value: null },
                                mirrorSampler: { type: 't', value: null },
                                alpha: { type: 'f', value: 1.0 },
                                time: { type: 'f', value: 0.0 },
                                distortionScale: { type: 'f', value: 20.0 },
                                noiseScale: { type: 'f', value: 1.0 },
                                textureMatrix: { type: 'm4', value: new THREE.Matrix4() },
                                sunColor: { type: 'c', value: new THREE.Color(0x7f7f7f) },
                                sunDirection: { type: 'v3', value: new THREE.Vector3(0.70707, 0.70707, 0) },
                                eye: { type: 'v3', value: new THREE.Vector3(0, 0, 0) },
                                waterColor: { type: 'c', value: new THREE.Color(0x555555) },
                            },
                        ]),
                        vertexShader: `
                  uniform mat4 textureMatrix;
                  uniform float time;

                  varying vec4 mirrorCoord;
                  varying vec3 worldPosition;
                  varying vec3 modelPosition;
                  varying vec3 surfaceX;
                  varying vec3 surfaceY;
                  varying vec3 surfaceZ;

                  void main() {
                    mirrorCoord = modelMatrix * vec4(position, 1.0);
                    worldPosition = mirrorCoord.xyz;
                    modelPosition = position;
                    surfaceX = vec3( modelMatrix[0][0], modelMatrix[0][1], modelMatrix[0][2]);
                    surfaceY = vec3( modelMatrix[1][0], modelMatrix[1][1], modelMatrix[1][2]);
                    surfaceZ = vec3( modelMatrix[2][0], modelMatrix[2][1], modelMatrix[2][2]);

                    mirrorCoord = textureMatrix * mirrorCoord;
                    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
                  }
                  `,
                        fragmentShader: `
                    uniform sampler2D mirrorSampler;
                    uniform float alpha;
                    uniform float time;
                    uniform float distortionScale;
                    uniform float noiseScale;
                    uniform sampler2D normalSampler;
                    uniform vec3 sunColor;
                    uniform vec3 sunDirection;
                    uniform vec3 eye;
                    uniform vec3 waterColor;
                    varying vec4 mirrorCoord;
                    varying vec3 worldPosition;
                    varying vec3 modelPosition;
                    varying vec3 surfaceX;
                    varying vec3 surfaceY;
                    varying vec3 surfaceZ;

      void sunLight(const vec3 surfaceNormal, const vec3 eyeDirection, in float shiny, in float spec, in float diffuse, inout vec3 diffuseColor, inout vec3 specularColor)
      {
        vec3 reflection = normalize(reflect(-sunDirection, surfaceNormal));
        float direction = max(0.0, dot(eyeDirection, reflection));
        specularColor += pow(direction, shiny) * sunColor * spec;
        diffuseColor += max(dot(sunDirection, surfaceNormal), 0.0) * sunColor * diffuse;
      }

      vec3 getNoise(in vec2 uv)
      {
        vec2 uv0 = uv / (103.0 * noiseScale) + vec2(time / 17.0, time / 29.0);
        vec2 uv1 = uv / (107.0 * noiseScale) - vec2(time / -19.0, time / 31.0);
        vec2 uv2 = uv / (vec2(8907.0, 9803.0) * noiseScale) + vec2(time / 101.0, time /   97.0);
        vec2 uv3 = uv / (vec2(1091.0, 1027.0) * noiseScale) - vec2(time / 109.0, time / -113.0);
        vec4 noise = texture2D(normalSampler, uv0) +
          texture2D(normalSampler, uv1) +
          texture2D(normalSampler, uv2) +
          texture2D(normalSampler, uv3);
        return noise.xyz * 0.5 - 1.0;
      }

      THREE.ShaderChunk[ "common" ]
      THREE.ShaderChunk[ "fog_pars_fragment" ]

      void main()
      {
        vec3 worldToEye = eye - worldPosition;
        vec3 eyeDirection = normalize(worldToEye);

      // Get noise based on the 3d position
        vec3 noise = getNoise(modelPosition.xy * 1.0);
        vec3 distordCoord = noise.x * surfaceX + noise.y * surfaceY;
        vec3 distordNormal = distordCoord + surfaceZ;

      // Revert normal if the eye is bellow the mesh
        if(dot(eyeDirection, surfaceZ) < 0.0)
          distordNormal = distordNormal * -1.0;

      // Compute diffuse and specular light (use normal and eye direction)
        vec3 diffuseLight = vec3(0.0);
        vec3 specularLight = vec3(0.0);
        sunLight(distordNormal, eyeDirection, 100.0, 2.0, 0.5, diffuseLight, specularLight);

      // Compute final 3d distortion, and project it to get the mirror sampling
        float distance = length(worldToEye);
        vec2 distortion = distordCoord.xy * distortionScale * sqrt(distance) * 0.07;
       vec3 mirrorDistord = mirrorCoord.xyz + vec3(distortion.x, distortion.y, 1.0);
       vec3 reflectionSample = texture2DProj(mirrorSampler, mirrorDistord).xyz;

      // Compute other parameters as the reflectance and the water appareance
        float theta = max(dot(eyeDirection, distordNormal), 0.0);
        float reflectance = 0.3 + (1.0 - 0.3) * pow((1.0 - theta), 3.0);
        vec3 scatter = max(0.0, dot(distordNormal, eyeDirection)) * waterColor;

      // Compute final pixel color
        vec3 albedo = mix(sunColor * diffuseLight * 0.3 + scatter, (vec3(0.1) + reflectionSample * 0.9 + reflectionSample * specularLight), reflectance);

       vec3 outgoingLight = albedo;
      THREE.ShaderChunk[ "fog_fragment" ]

       gl_FragColor = vec4( outgoingLight, alpha );
      }
    }`,
                    })
                }
                position={[0, -0.03, 0]}
            />
            <mesh name="Terrain_remesh" geometry={nodes.Terrain_remesh.geometry} material={materials['Mat.2']} />
            <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
                position={[-0.61, 0.04, 0.23]}
                rotation={[0, Math.PI / 9, 0]}
            />
            <mesh
                name="Sand"
                geometry={nodes.Sand.geometry}
                material={materials.Sand}
                position={[0.04, 0, -0.96]}
                rotation={[0, -0.44, 0]}
            />
            <mesh
                name="Cross"
                geometry={nodes.Cross.geometry}
                material={materials.WhiteLine}
                position={[-0.58, 0, -1.18]}
                rotation={[0, -0.43, 0]}
            />
            <mesh
                name="Cube7"
                geometry={nodes.Cube7.geometry}
                material={materials.Wood}
                position={[-2.01, 0.04, 0.29]}
                rotation={[0, -0.56, 0]}
            />
            <mesh name="Sand6" geometry={nodes.Sand6.geometry} material={materials.WhiteLine} />
            <mesh name="Sand3" geometry={nodes.Sand3.geometry} material={materials.WhiteLine} />
            <mesh name="Cube4_0" geometry={nodes.Cube4_0.geometry} material={nodes.Cube4_0.material} />
            <mesh name="Cross1" geometry={nodes.Cross1.geometry} material={materials.WhiteLine} />
            <mesh
                name="Pool"
                geometry={nodes.Pool.geometry}
                material={materials.PoolColor}
                position={[-3, -0.04, -0.57]}
                rotation={[0, 0.04, 0]}
            />
            <mesh
                name="Sand_1"
                geometry={nodes.Sand_1.geometry}
                material={materials.Grass}
                position={[0.46, 0, -0.77]}
                rotation={[0, -0.44, 0]}
            />
            <mesh
                name="Sand_2"
                geometry={nodes.Sand_2.geometry}
                material={materials.CourtColor}
                position={[0.2, 0, -0.88]}
                rotation={[0, -0.44, 0]}
            />
        </group>
    );
}

useGLTF.preload('/model-transformed.glb');
