/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/Pech.glb -o ./src/components/Pech.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Floor1: THREE.Mesh;
        Floor: THREE.Mesh;
        Photo1: THREE.Mesh;
        SphereNejno: THREE.Mesh;
        Picture: THREE.Mesh;
        Mainstage: THREE.Mesh;
        Golden: THREE.Mesh;
        Drokino: THREE.Mesh;
        Polygon_22: THREE.Mesh;
        Polygon_61: THREE.Mesh;
        Polygon_11: THREE.Mesh;
        Polygon_52: THREE.Mesh;
        Polygon_2: THREE.Mesh;
        Polygon_10: THREE.Mesh;
        Polygon_2_1: THREE.Mesh;
        Polygon_0: THREE.Mesh;
    };
    materials: {
        ['Mat.10']: THREE.MeshStandardMaterial;
        Floor: THREE.MeshStandardMaterial;
        Polaroid1: THREE.MeshStandardMaterial;
        ['Mat.8']: THREE.MeshStandardMaterial;
        MainStage: THREE.MeshStandardMaterial;
        ['Mat.9']: THREE.MeshStandardMaterial;
        ['Mat.5']: THREE.MeshStandardMaterial;
        Flowers: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/model/Pech-transformed.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Floor1.geometry} material={materials['Mat.10']} />
            <mesh castShadow receiveShadow geometry={nodes.Floor.geometry} material={materials.Floor} />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Photo1.geometry}
                material={materials.Polaroid1}
                position={[0.01, 0.093, 5.355]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereNejno.geometry}
                material={materials['Mat.8']}
                position={[0.018, 0.536, -0.176]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Picture.geometry}
                material={materials.MainStage}
                position={[1.104, 0.854, -6.119]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mainstage.geometry}
                material={materials['Mat.9']}
                position={[1.104, 0.854, -6.119]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Golden.geometry}
                material={nodes.Golden.material}
                position={[0.753, 1.522, -1.162]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Drokino.geometry}
                material={materials['Mat.5']}
                position={[-0.821, 0.649, -8.849]}
            />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_22.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_61.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_11.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_52.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_2.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_10.geometry} material={materials.Flowers} />
            <mesh castShadow receiveShadow geometry={nodes.Polygon_2_1.geometry} material={materials.Flowers} />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polygon_0.geometry}
                material={materials.Flowers}
                position={[-0.528, 0.482, -0.673]}
                rotation={[0.974, 0.738, 1.454]}
            />
        </group>
    );
}

useGLTF.preload('/model/Pech-transformed.glb');
