/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/Rombich.glb -o ./src/components/Rombich.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';
import { useControls } from 'leva';
import { useIsDayState } from '@/atoms/is-day';
import { gsap } from 'gsap';
import { useScreensState } from '@/atoms/screens';

type GLTFResult = GLTF & {
    nodes: {
        Drokino001: THREE.Mesh;
        Floor001: THREE.Mesh;
        Flowers1001: THREE.Mesh;
        Golden001: THREE.Mesh;
        Mainstage001: THREE.Mesh;
        Malbert001: THREE.Mesh;
        Photo1001: THREE.Mesh;
        SphereDarkGreen001: THREE.Mesh;
        SphereGreen001: THREE.Mesh;
        SphereNejno001: THREE.Mesh;
        SphereOrange001: THREE.Mesh;
        SphereRed001: THREE.Mesh;
    };
    materials: {
        DrokinoHomes: THREE.MeshStandardMaterial;
        Floor: THREE.MeshStandardMaterial;
        Flowers: THREE.MeshStandardMaterial;
        Picture: THREE.MeshStandardMaterial;
        MainStage: THREE.MeshStandardMaterial;
        Malbert_0: THREE.MeshStandardMaterial;
        Polaroid1: THREE.MeshStandardMaterial;
        GreenDark: THREE.MeshStandardMaterial;
        BlueGreen: THREE.MeshStandardMaterial;
        Mat: THREE.MeshStandardMaterial;
        Orange: THREE.MeshStandardMaterial;
        Red: THREE.MeshStandardMaterial;
    };
};

type Props = {
    opacity: React.MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];

export function Model({ opacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/model/Rombich-transformed.glb') as GLTFResult;
    const [isDayState] = useIsDayState();
    const [screensState] = useScreensState();
    const [isDrokinoHovered, setIsDrokinoHovered] = useState(false);
    const [isAnimating, setIsAnimating] = useState(false);
    const drokinoEl = useRef<THREE.Mesh>();

    useEffect(() => {
        if (drokinoEl.current) {
            if (isDrokinoHovered && !isAnimating) {
                setIsAnimating(true);
                gsap.timeline({
                    onComplete: () => {
                        setIsAnimating(false);
                    },
                })
                    .to(
                        drokinoEl.current.rotation,
                        {
                            y: -Math.PI / 4,
                            ease: 'power4.out',
                            duration: 2,
                        },
                        0,
                    )
                    .to(
                        drokinoEl.current.scale,
                        {
                            y: 0.0125,
                            ease: 'power4.out',
                            duration: 2,
                        },
                        0,
                    );
            }

            if (!isDrokinoHovered && !isAnimating) {
                gsap.timeline({
                    onComplete: () => {
                        setIsAnimating(false);
                    },
                })
                    .to(
                        drokinoEl.current.rotation,
                        {
                            y: 0,
                            ease: 'power4.out',
                            duration: 2,
                        },
                        0,
                    )
                    .to(
                        drokinoEl.current.scale,
                        {
                            y: 0.01,
                            ease: 'power4.out',
                            duration: 2,
                        },
                        0,
                    );
            }
        }
    }, [isDrokinoHovered, isAnimating]);

    useEffect(() => {
        document.documentElement.style.cursor = isDrokinoHovered ? 'pointer' : 'default';

        return () => {
            document.documentElement.style.cursor = 'default';
        };
    }, [isDrokinoHovered]);

    // const { intensity, lowIntensity, lowestIntensity, highIntensity } = useControls('model', {
    //     intensity: { value: 1, min: 0.1, max: 6, step: 0.1 },
    //     lowIntensity: { value: 0.5, min: 0.1, max: 6, step: 0.1 },
    //     lowestIntensity: { value: 0.25, min: 0.1, max: 6, step: 0.1 },
    //     highIntensity: { value: 6, min: 0.1, max: 6, step: 0.1 },
    // });

    const intensity = isDayState ? 1.2 : 0.9;
    const lowIntensity = isDayState ? 0.75 : 1;
    const lowestIntensity = isDayState ? 1 : 1;
    const highIntensity = isDayState ? 6 : 6;

    useMemo(() => {
        Object.values(materials).forEach((material) => {
            material.transparent = true;
            material.opacity = 0;
        });
    }, [materials]);

    useFrame(() => {
        if (opacity.current) {
            Object.values(materials).forEach((material) => {
                material.opacity = opacity.current;
            });
        }
    });

    return (
        <group {...props} dispose={null}>
            <mesh
                // castShadow
                // receiveShadow
                ref={drokinoEl}
                geometry={nodes.Drokino001.geometry}
                material={materials.DrokinoHomes}
                position={[-0.821, 0.649, -8.849]}
                scale={0.01}
                material-envMapIntensity={lowIntensity}
                onPointerEnter={(obj) => {
                    if (screensState === 9 || screensState === 8) {
                        setIsDrokinoHovered(true);
                        // gsap.to(obj.eventObject.rotation, {
                        //     y: -Math.PI / 4,
                        //     ease: 'expo.out',
                        //     duration: 1.5,
                        //     onComplete: () => {
                        //         setIsAnimating(false);
                        //     },
                        // });
                    }
                }}
                onPointerLeave={(obj) => {
                    // if (isAnimating) {
                    //     setTimeout(() => {
                    //         gsap.to(obj.eventObject.rotation, {
                    //             y: 0,
                    //             ease: 'expo.out',
                    //             duration: 1.5,
                    //         });
                    //     }, 1500);
                    // } else {
                    //     if (screensState === 9 || screensState === 8) {
                    //         gsap.to(obj.eventObject.rotation, {
                    //             y: 0,
                    //             ease: 'expo.out',
                    //             duration: 1.5,
                    //         });
                    //     }
                    // }
                    setIsDrokinoHovered(false);
                }}
                onClick={() => {
                    window.open('https://go.2gis.com/g1i2j', '_blank');
                }}
                // material-envMapIntensity={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Floor001.geometry}
                material={materials.Floor}
                scale={0.01}
                material-envMapIntensity={intensity}
            />

            <Float speed={2} floatIntensity={0.2} rotationIntensity={0.12}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Flowers1001.geometry}
                    material={materials.Flowers}
                    position={[-0.932, 0.511, -0.35]}
                    scale={0.01}
                    material-envMapIntensity={intensity}
                />
            </Float>

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Golden001.geometry}
                material={materials.Picture}
                position={[0.753, 1.522, -1.162]}
                scale={0.01}
                material-envMapIntensity={highIntensity}
                // material-envMapIntensity={6}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mainstage001.geometry}
                material={materials.MainStage}
                position={[1.104, 0.854, -6.119]}
                scale={0.01}
                material-envMapIntensity={intensity}
            />
            <mesh
                castShadow
                // receiveShadow
                geometry={nodes.Malbert001.geometry}
                material={materials.Malbert_0}
                position={[1.104, 0.854, -6.119]}
                scale={0.01}
                material-envMapIntensity={lowIntensity}
                // material-envMapIntensity={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Photo1001.geometry}
                material={materials.Polaroid1}
                position={[0.01, 0.093, 5.355]}
                scale={0.01}
                material-envMapIntensity={lowestIntensity}
                // material-envMapIntensity={0.25}
            />
            <Float speed={2} floatIntensity={0.2} rotationIntensity={0.12}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SphereDarkGreen001.geometry}
                    material={materials.GreenDark}
                    position={[-0.382, 0.561, 0.004]}
                    scale={0.01}
                    material-envMapIntensity={intensity}
                />
            </Float>
            <Float speed={2} floatIntensity={0.2} rotationIntensity={0.12}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SphereGreen001.geometry}
                    material={materials.BlueGreen}
                    position={[-0.186, 0.507, 0.159]}
                    scale={0.01}
                    material-envMapIntensity={intensity}
                />
            </Float>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereNejno001.geometry}
                material={materials.Mat}
                position={[-0.068, 0.465, -0.778]}
                scale={0.01}
                material-envMapIntensity={intensity}
            />

            <Float speed={2} floatIntensity={0.2} rotationIntensity={0.12}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SphereOrange001.geometry}
                    material={materials.Orange}
                    position={[0.418, 0.606, 0.425]}
                    scale={0.01}
                    material-envMapIntensity={intensity}
                />
            </Float>
            <Float speed={2} floatIntensity={0.2} rotationIntensity={0.12}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SphereRed001.geometry}
                    material={materials.Red}
                    position={[0.188, 0.466, -0.735]}
                    scale={0.01}
                    material-envMapIntensity={intensity}
                />
            </Float>
        </group>
    );
}

useGLTF.preload('/model/Rombich-transformed.glb');
