/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/VrodeOno.glb -o ./src/components/VrodeOno.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
    nodes: {
        Drokino001: THREE.Mesh;
        Floor001: THREE.Mesh;
        Flowers1001: THREE.Mesh;
        Golden001: THREE.Mesh;
        Mainstage001: THREE.Mesh;
        Malbert001: THREE.Mesh;
        Photo1001: THREE.Mesh;
        SphereDarkGreen001: THREE.Mesh;
        SphereGreen001: THREE.Mesh;
        SphereNejno001: THREE.Mesh;
        SphereOrange001: THREE.Mesh;
        SphereRed001: THREE.Mesh;
    };
    materials: {
        DrokinoHomes: THREE.MeshStandardMaterial;
        Floor: THREE.MeshStandardMaterial;
        Flowers: THREE.MeshStandardMaterial;
        Picture: THREE.MeshStandardMaterial;
        MainStage: THREE.MeshStandardMaterial;
        Malbert_0: THREE.MeshStandardMaterial;
        Polaroid1: THREE.MeshStandardMaterial;
        GreenDark: THREE.MeshStandardMaterial;
        BlueGreen: THREE.MeshStandardMaterial;
        Mat: THREE.MeshStandardMaterial;
        Orange: THREE.MeshStandardMaterial;
        Red: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/model/VrodeOno-transformed.glb') as GLTFResult;
    const ref = useRef();

    useFrame((state, delta) => {
        // ref.current.rotation.y += delta / 10;
    });

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Drokino001.geometry}
                material={materials.DrokinoHomes}
                position={[-0.821, 0.649, -8.849]}
                scale={0.01}
            />
            <mesh castShadow receiveShadow geometry={nodes.Floor001.geometry} material={materials.Floor} scale={0.01} />
            <mesh
                castShadow
                receiveShadow
                ref={ref}
                geometry={nodes.Flowers1001.geometry}
                material={materials.Flowers}
                position={[-0.932, 0.511, -0.35]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Golden001.geometry}
                material={materials.Picture}
                position={[0.753, 1.522, -1.162]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mainstage001.geometry}
                material={materials.MainStage}
                position={[1.104, 0.854, -6.119]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Malbert001.geometry}
                material={materials.Malbert_0}
                position={[1.104, 0.854, -6.119]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Photo1001.geometry}
                material={materials.Polaroid1}
                position={[0.01, 0.093, 5.355]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereDarkGreen001.geometry}
                material={materials.GreenDark}
                position={[-0.382, 0.561, 0.004]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereGreen001.geometry}
                material={materials.BlueGreen}
                position={[-0.186, 0.507, 0.159]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereNejno001.geometry}
                material={materials.Mat}
                position={[-0.068, 0.465, -0.778]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereOrange001.geometry}
                material={materials.Orange}
                position={[0.418, 0.606, 0.425]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SphereRed001.geometry}
                material={materials.Red}
                position={[0.188, 0.466, -0.735]}
                scale={0.01}
            />
        </group>
    );
}

useGLTF.preload('/model/VrodeOno-transformed.glb');
