/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/tree1.glb -o ./src/components/TreeOne.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useRef, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
    nodes: {
        _3_tree__3_tree_0: THREE.Mesh;
    };
    materials: {
        ['3_tree']: THREE.MeshStandardMaterial;
    };
};

type Props = {
    sceneOpacity: React.MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];

export function TreeOne({ sceneOpacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/model/trees/tree1-transformed.glb') as GLTFResult;

    useMemo(() => {
        Object.values(materials).forEach((material) => {
            material.transparent = true;
            material.opacity = 0;
        });
    }, [materials]);

    useFrame(() => {
        if (sceneOpacity.current) {
            Object.values(materials).forEach((material) => {
                material.opacity = sceneOpacity.current;
            });
        }
    });

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes._3_tree__3_tree_0.geometry}
                material={materials['3_tree']}
                position={[-1.339, -0.012, 0.024]}
                rotation={[-0.359, -0.228, -0.067]}
                scale={[0.204, 0.254, 0.204]}
            />
        </group>
    );
}

useGLTF.preload('/model/trees/tree1-transformed.glb');
