/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/tree6.glb -o ./src/components/TreeSix.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useRef, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { useControls } from 'leva';

type GLTFResult = GLTF & {
    nodes: {
        _6_tree__6_tree_0: THREE.Mesh;
    };
    materials: {
        ['6_tree']: THREE.MeshStandardMaterial;
    };
};

type Props = {
    sceneOpacity: React.MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];

export function TreeSix({ sceneOpacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/model/trees/tree6-transformed.glb') as GLTFResult;

    useMemo(() => {
        Object.values(materials).forEach((material) => {
            material.transparent = true;
            material.opacity = 0;
        });
    }, [materials]);

    useFrame(() => {
        if (sceneOpacity.current) {
            Object.values(materials).forEach((material) => {
                material.opacity = sceneOpacity.current;
            });
        }
    });

    // const { intensity } = useControls('treesix', {
    //     intensity: 2.5,
    // });

    const intensity = 1.5;

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                // receiveShadow
                geometry={nodes._6_tree__6_tree_0.geometry}
                material={materials['6_tree']}
                position={[2.567, -0.023, 0.034]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.135}
                material-envMapIntensity={intensity}
            />
        </group>
    );
}

useGLTF.preload('/model/trees/tree6-transformed.glb');
