/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/tree4.glb -o ./src/components/TreeFour.tsx -t -T -s
*/

import React, { useRef, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
    nodes: {
        _4_tree__4_tree_0: THREE.Mesh;
    };
    materials: {
        ['4_tree']: THREE.MeshStandardMaterial;
    };
};

type Props = {
    sceneOpacity: React.MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];

export function TreeFour({ sceneOpacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/model/trees/tree4-transformed.glb') as GLTFResult;

    useMemo(() => {
        Object.values(materials).forEach((material) => {
            material.transparent = true;
            material.opacity = 0;
        });
    }, [materials]);

    useFrame(() => {
        if (sceneOpacity.current) {
            Object.values(materials).forEach((material) => {
                material.opacity = sceneOpacity.current;
            });
        }
    });

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                // receiveShadow
                geometry={nodes._4_tree__4_tree_0.geometry}
                material={materials['4_tree']}
                position={[-0.182, -0.012, 0.024]}
                rotation={[2.586, -1.382, -2.872]}
                scale={[0.077, 0.144, 0.047]}
            />
        </group>
    );
}

useGLTF.preload('/model/trees/tree4-transformed.glb');
