/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/model/tree7.glb -o ./src/components/TreeSeven.tsx -t -T -s
*/

import * as THREE from 'three';
import React, { useRef, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { useControls } from 'leva';

type GLTFResult = GLTF & {
    nodes: {
        _7_tree__7_tree_0: THREE.Mesh;
    };
    materials: {
        ['7_tree']: THREE.MeshStandardMaterial;
    };
};

type Props = {
    sceneOpacity: React.MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];

export function TreeSeven({ sceneOpacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/model/trees/tree7-transformed.glb') as GLTFResult;

    useMemo(() => {
        Object.values(materials).forEach((material) => {
            material.transparent = true;
            material.opacity = 0;
        });
    }, [materials]);

    useFrame(() => {
        if (sceneOpacity.current) {
            Object.values(materials).forEach((material) => {
                material.opacity = sceneOpacity.current;
            });
        }
    });

    // const { intensity } = useControls('treeseven', {
    //     intensity: 2.5,
    // });

    const intensity = 1.5;

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                // receiveShadow
                geometry={nodes._7_tree__7_tree_0.geometry}
                material={materials['7_tree']}
                position={[4.038, -0.012, 0.024]}
                rotation={[-1.22, 0.041, -2.69]}
                scale={[0.294, 0.294, 0.408]}
                material-envMapIntensity={intensity}
            />
        </group>
    );
}

useGLTF.preload('/model/trees/tree7-transformed.glb');
