import { PersonData } from './types';

export const guestData: PersonData[] = [
    {
        hash: '044adea5',
        names: 'Евгений и Полина',
        welcome: '<3',
        accept_script_id: 'AKfycbyOy53ZUFKptENk1Rc7p36VdPFgEpjRbqEKF8bNWQ3ms0RELUKtuFBl2TozEAijxfCQ',
        decline_script_id: 'AKfycbweit0DiOvNFSTRXA_azV_8Y7WVNhErMaEuD4wZCo0_DbV4srLN4ye_byGbMqU5vKb6',
    },
    {
        hash: '1c867f21',
        names: 'Виктор и Дарья',
        welcome: '<3',
        accept_script_id: 'AKfycbzC795iVOsfkhaI299mC29F-cnIOuD6jWkV93zqccmciosAb13wV9lTYnJ9pSenH98',
        decline_script_id: 'AKfycbymraPQxFO1rEJd7W2c_eeDbpaj7r4lWlN3KJfm3V0B_YFW38kp01T5_QPPaF4Aw_11',
    },
    {
        hash: '6bca9b82',
        names: 'Артём и Анастасия',
        welcome: '<3',
        accept_script_id: 'AKfycbyDERXSrCTqXqsxKq2G3Q0MdY8z1dYZBi2YbuFmAnZYIZtN55Th2uhg1B73Xc6VIL5z',
        decline_script_id: 'AKfycbxTmQzGDV6DOQic_LjL8Nms9Cxu6kAHVN4HWVveoKjvJR6pDHuP1qos6H_zGAxy7bSh',
    },
    {
        hash: 'e940c2a6',
        names: 'Сергей и Екатерина',
        welcome: '<3',
        accept_script_id: 'AKfycbxC2AAzxo8h_PHISOEtrtAthKQRSyr59UTqjWQ83YttiS8fSVODJLhAXdy1f-QldB9G',
        decline_script_id: 'AKfycbwPoKP_91ssS4bP6stOxur1lz3PObyOmvYRFuDVDPLRq9XX_PxRFtZnIDUAP_Mddxw-',
    },
    {
        hash: '71def424',
        names: 'Ринат + 1',
        welcome: '<3',
        accept_script_id: 'AKfycbwOaPJi3WU9wu2TTFCYfn5yXBac0qU2mP5t-iWs1VIHBFQyTKQwlRSmczcR09Q3MyDr',
        decline_script_id: 'AKfycbwj9mBPQ6M22VqAhc_AeET6hjmu3uIrESKCmpxznKZgs-d4iKpSbC_1YA8JW1uq7ZIc',
    },
    {
        hash: '6ad0800b',
        names: 'Глеб и Алёна',
        welcome: '<3',
        accept_script_id: 'AKfycbx87PzYLRloxJUA5L1fYNDUtaD-951T46qnTpJ05VEKNo1CeVvuG_o_Q7BdFlCAqR9z',
        decline_script_id: 'AKfycbyZpvFe8uCfJwXYYCtbSC9iTqsI1eRt45xszSW9QiKv_umkwHK_r-7OdyfkVqEBKBHn',
    },
    {
        hash: '44113cd1',
        names: 'Артём и Юлия',
        welcome: '<3',
        accept_script_id: 'AKfycbwG5MU_BTkGF8bF5m17-b2sLJQg9DVw4ZjTw_YszGlxW9cbCi2A16ESGMAyqwY69sGq',
        decline_script_id: 'AKfycbzGyeIG8XYqoPm_Az8t8EOQ2jLWry9WJu7FLsiXxy9RhSEsW1N1LMvZke6-UPOhbmWT',
    },
    {
        hash: '30718bb7',
        names: 'Андрей и Дарья',
        welcome: '<3',
        accept_script_id: 'AKfycbxjEf7l996zCDabkqJrxjD5ZXg-YMMKrxuJPsPXObPGRS6Sjrqw_6WLfe3Kl3OdFHEX',
        decline_script_id: 'AKfycbza7UWzXhxtFoLj-Ty04PtFBlPnTnIJ6nz2JiAthupzUk08azWs6J5UtC9zF7qeWxM',
    },
    {
        hash: '4bf671ff',
        names: 'Никита и Лиза',
        welcome: '<3',
        accept_script_id: 'AKfycbyxUPMsq3N7gyG2OMn-2pR0Zoep0Y5S-BJLWo-3zjsXJf5xgtGZDAxpU78_YDjI_XVM',
        decline_script_id: 'AKfycbyiBZRM1Rg9h6FI0pLInRcpvUImfuTK1Y6xG-Ne_jTRnZYZd2EdewiqOxV1AsBflQNu',
    },
    {
        hash: 'b36c8224',
        names: 'Алексей и Екатерина',
        welcome: '<3',
        accept_script_id: 'AKfycbzachyLKg8G5JUGBH41WHFkaRCvITivVTqzvSEAI5Y4lDScOpd12QXwmIribYjuYrE3',
        decline_script_id: 'AKfycbxThvNehbS8ILe_DoTlfwQ8FISmxpYdEt5rKP7LtbopqyS93LJDejQxESlV_yPwEgpu',
    },
    {
        hash: 'd7a3b130',
        names: 'Павел и Влада',
        welcome: '<3',
        accept_script_id: 'AKfycbz9e8S64HcoGsG-Z-qXoe3tqTRRox9QSauDq-lWIyZHW-QeY-OMQSUPtxiL4R5uEhhH',
        decline_script_id: 'AKfycbxqqOXmW3Sn6ihCx44bk-CHYG0XSwo_RY_PjZ8FxdSSjXlnFFbZPbNdn3nFP7kPAAuW',
    },
    {
        hash: '2b72bb68',
        names: 'Сергей и Татьяна',
        welcome: '<3',
        accept_script_id: 'AKfycbzGWJcrv4QzquGBvceWURb8ZkZlxx9laBmSXE75mxnnvDWm8TE6QQ6yOSfPd0fELmWy',
        decline_script_id: 'AKfycby15k5lilzRGunbi7cYO2aL0QZSRqeqauv8RZKHd_yu8FT2mgsaR36vrTj27cq7gssg',
    },
    {
        hash: '0d47ab19',
        names: 'Дмитрий и Надежда',
        welcome: '<3',
        accept_script_id: 'AKfycbz3fkAQxL3Ot5po1fqhEBpcw_NC0nWtRI6Cgh38lwauuk6aDrRIKy3VRuAkcsHraAmR',
        decline_script_id: 'AKfycbwOu2EKtIg2dFhdv3_SdxS3hB8G_ShOH1aKhGr6cq_m_YgLAQuAk-ko05X01jfF-jk',
    },
    {
        hash: '8d0815f7',
        names: 'Ростислав и Александра',
        welcome:
            'Брат, шашлычник сказал не придёт, приезжай. Саша, а тебя приглашаем, как званого гостя, будем очень рады вас увидеть!',
        accept_script_id: 'AKfycbyJdGxBBfPIp3UO8H-a9pZPEFz-I6aravmLK5cWUU2XFYpy_Dz6BChWSc78aQbs_fa1',
        decline_script_id: 'AKfycbzxJgLjNYIyIJ9qPNdmnybgwdmPm49R8yG28CwxSTlI1ESbdtyT1NJEMB_mAfOz-oH1',
    },
    {
        hash: 'b862117f',
        names: 'Артём и Екатерина',
        welcome: '<3',
        accept_script_id: 'AKfycbydSm4pd_4uWK2ukkjz4wbzfKHWWgg6DB8vnPcEKDOSMNAjJQU--r__46NdQpmSKTs_',
        decline_script_id: 'AKfycbyHgcUbbWURnUNMsbAk4TUaDdKRakKKgg2zMM931usJb1VKglUVELtZaYSURcNIk27Q',
    },
    {
        hash: '32384ebd',
        names: 'Никита и Соня',
        welcome: '<3',
        accept_script_id: 'AKfycbypO8-9Kri6CxW1fGWrbE2QiCZXT21eFWvXmA5objW1vGOc5HmJKKEvnnDGTBzQZmC9',
        decline_script_id: 'AKfycbzAd84oRX7h3cV-0591y4fgckQulXEYbvV5tvPzhrEbMXr2UEs6dXI5tm07pOAxyblk',
    },
    {
        hash: 'c543e9f4',
        names: 'Света и Алексей',
        welcome: '<3',
        accept_script_id: 'AKfycbz410hxrhGT_BeruYsgtZVGQQdBMRiCqyyQ6SkSsfjyFzttvP7WNFRgPnSOUy2PlGl6',
        decline_script_id: 'AKfycbwZjXQXf4nkzGx1uWi2Vn0BcDwaynrdaBfRmC-PU-_Xi-REImpYphT6qUfWFBNy5R9M',
    },
    {
        hash: '2b4a3ee0',
        names: 'Елена и Валерий',
        welcome: '<3',
        accept_script_id: 'AKfycbwgd2ndScOyaaINf7tSx9uJHfoZqePA6TRZUHfmm4uldoLCyB7IJ1cgov_H1xhlV6On',
        decline_script_id: 'AKfycby9S9AbCe6S06Idbe5QOV67Gn5TxqjSlS45SW44YH4S5_WHwije7Od-2cAIHdp4F4zE',
    },
];
