/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 model.glb -t -k -K -T
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Route_1: THREE.Mesh
    Pool: THREE.Mesh
    Cube4_1: THREE.Mesh
    Sand6: THREE.Mesh
    Sand5: THREE.Mesh
    Sand9: THREE.Mesh
    Sand4: THREE.Mesh
    Sand3: THREE.Mesh
    Sand2: THREE.Mesh
    Sand1: THREE.Mesh
    Sand_1: THREE.Mesh
    Sand7: THREE.Mesh
    Sand8: THREE.Mesh
    Sand6_1: THREE.Mesh
    Sand5_1: THREE.Mesh
    Sand9_1: THREE.Mesh
    Sand4_1: THREE.Mesh
    Sand3_1: THREE.Mesh
    Sand2_1: THREE.Mesh
    Sand1_1: THREE.Mesh
    Sand7_1: THREE.Mesh
    Sand8_1: THREE.Mesh
    Sand_2: THREE.Mesh
    Sand6_2: THREE.Mesh
    Sand5_2: THREE.Mesh
    Sand9_2: THREE.Mesh
    Sand4_2: THREE.Mesh
    Sand3_2: THREE.Mesh
    Sand2_2: THREE.Mesh
    Sand1_2: THREE.Mesh
    Sand7_2: THREE.Mesh
    Sand8_2: THREE.Mesh
    Sand_3: THREE.Mesh
    Sand6_3: THREE.Mesh
    Sand5_3: THREE.Mesh
    Sand9_3: THREE.Mesh
    Sand4_3: THREE.Mesh
    Sand3_3: THREE.Mesh
    Sand2_3: THREE.Mesh
    Sand1_3: THREE.Mesh
    Sand7_3: THREE.Mesh
    Sand8_3: THREE.Mesh
    Sand_4: THREE.Mesh
    Cube4_0: THREE.Mesh
    Cube4_1_1: THREE.Mesh
    Cube4_2: THREE.Mesh
    Cube4_3: THREE.Mesh
    Cube4_4: THREE.Mesh
    Cube4_5: THREE.Mesh
    Cube4_6: THREE.Mesh
    Cube4_7: THREE.Mesh
    Cube4_8: THREE.Mesh
    Cube4_9: THREE.Mesh
    Cube4_10: THREE.Mesh
    Cube4_11: THREE.Mesh
    Cube4_12: THREE.Mesh
    Cube4_13: THREE.Mesh
    Cube4_14: THREE.Mesh
    Cube4_15: THREE.Mesh
    Cube4_16: THREE.Mesh
    Cube4_17: THREE.Mesh
    Cube4_18: THREE.Mesh
    Cube4_19: THREE.Mesh
    Cube4_20: THREE.Mesh
    Cube4_0_1: THREE.Mesh
    Cube4_1_2: THREE.Mesh
    Cube4_2_1: THREE.Mesh
    Cube4_3_1: THREE.Mesh
    Cube4_4_1: THREE.Mesh
    Cube4_5_1: THREE.Mesh
    Cube4_6_1: THREE.Mesh
    Cube4_7_1: THREE.Mesh
    Cube4_8_1: THREE.Mesh
    Cube4_9_1: THREE.Mesh
    Cube4_10_1: THREE.Mesh
    Cube4_11_1: THREE.Mesh
    Cube4_12_1: THREE.Mesh
    Cube4_13_1: THREE.Mesh
    Cube4_14_1: THREE.Mesh
    Cube4_15_1: THREE.Mesh
    Cube4_16_1: THREE.Mesh
    Cube4_17_1: THREE.Mesh
    Cube4_18_1: THREE.Mesh
    Cube4_19_1: THREE.Mesh
    Cube4_20_1: THREE.Mesh
    Water: THREE.Mesh
    Terrain_remesh: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder1: THREE.Mesh
    Sweep: THREE.Mesh
    Sweep1: THREE.Mesh
    Cube: THREE.Mesh
    Cube1: THREE.Mesh
    Cube2: THREE.Mesh
    Cube6: THREE.Mesh
    Cube3: THREE.Mesh
    Sand: THREE.Mesh
    Cube4: THREE.Mesh
    Cube5: THREE.Mesh
    Cross1: THREE.Mesh
    Cross2: THREE.Mesh
    Cross3: THREE.Mesh
    Cross4: THREE.Mesh
    Cross5: THREE.Mesh
    Cross6: THREE.Mesh
    Cross7: THREE.Mesh
    Cross: THREE.Mesh
    Cube7: THREE.Mesh
  }
  materials: {
    Sand: THREE.MeshStandardMaterial
    PoolColor: THREE.MeshStandardMaterial
    WhiteLine: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    CourtColor: THREE.MeshStandardMaterial
    WAter: THREE.MeshStandardMaterial
    ['Mat.2']: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model-transformed.glb') as GLTFResult;

  console.log(nodes.Cube4_1_2);
  return (
    <group {...props} dispose={null}>
      <group>
        <group name="Route">
          <mesh name="Route_1" geometry={nodes.Route_1.geometry} material={materials.Sand} />
        </group>
        <group name="Boole" position={[-3, -0.04, -0.57]} rotation={[0, 0.04, 0]}>
          <mesh name="Pool" geometry={nodes.Pool.geometry} material={materials.PoolColor} />
          <mesh name="Cube4_1" geometry={nodes.Cube4_1.geometry} material={materials.PoolColor} position={[0.01, -0.14, -0.01]} />
        </group>
        <group name="Tennis" position={[0.09, 0, -0.93]}>
          <group name="Court3" position={[0.37, 0, 0.16]}>
            <mesh name="Sand6" geometry={nodes.Sand6.geometry} material={materials.WhiteLine} position={[-0.06, -0.01, 0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand5" geometry={nodes.Sand5.geometry} material={materials.WhiteLine} position={[0.06, -0.01, -0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand9" geometry={nodes.Sand9.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand4" geometry={nodes.Sand4.geometry} material={materials.WhiteLine} position={[0, 0.03, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand3" geometry={nodes.Sand3.geometry} material={materials.WhiteLine} position={[-0.09, -0.01, -0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand2" geometry={nodes.Sand2.geometry} material={materials.WhiteLine} position={[0.09, -0.01, 0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand1" geometry={nodes.Sand1.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand_1" geometry={nodes.Sand_1.geometry} material={materials.Grass} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand7" geometry={nodes.Sand7.geometry} material={materials.WhiteLine} position={[-0.09, 0.02, -0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand8" geometry={nodes.Sand8.geometry} material={materials.WhiteLine} position={[0.09, 0.02, 0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
          </group>
          <group name="Court2" position={[0.12, 0, 0.05]}>
            <mesh name="Sand6_1" geometry={nodes.Sand6_1.geometry} material={materials.WhiteLine} position={[-0.06, -0.01, 0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand5_1" geometry={nodes.Sand5_1.geometry} material={materials.WhiteLine} position={[0.06, -0.01, -0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand9_1" geometry={nodes.Sand9_1.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand4_1" geometry={nodes.Sand4_1.geometry} material={materials.WhiteLine} position={[0, 0.03, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand3_1" geometry={nodes.Sand3_1.geometry} material={materials.WhiteLine} position={[-0.09, -0.01, -0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand2_1" geometry={nodes.Sand2_1.geometry} material={materials.WhiteLine} position={[0.09, -0.01, 0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand1_1" geometry={nodes.Sand1_1.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand7_1" geometry={nodes.Sand7_1.geometry} material={materials.WhiteLine} position={[-0.09, 0.02, -0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand8_1" geometry={nodes.Sand8_1.geometry} material={materials.WhiteLine} position={[0.09, 0.02, 0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand_2" geometry={nodes.Sand_2.geometry} material={materials.CourtColor} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
          </group>
          <group name="Court1" position={[-0.12, 0, -0.05]}>
            <mesh name="Sand6_2" geometry={nodes.Sand6_2.geometry} material={materials.WhiteLine} position={[-0.06, -0.01, 0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand5_2" geometry={nodes.Sand5_2.geometry} material={materials.WhiteLine} position={[0.06, -0.01, -0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand9_2" geometry={nodes.Sand9_2.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand4_2" geometry={nodes.Sand4_2.geometry} material={materials.WhiteLine} position={[0, 0.03, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand3_2" geometry={nodes.Sand3_2.geometry} material={materials.WhiteLine} position={[-0.09, -0.01, -0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand2_2" geometry={nodes.Sand2_2.geometry} material={materials.WhiteLine} position={[0.09, -0.01, 0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand1_2" geometry={nodes.Sand1_2.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand7_2" geometry={nodes.Sand7_2.geometry} material={materials.WhiteLine} position={[-0.09, 0.02, -0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand8_2" geometry={nodes.Sand8_2.geometry} material={materials.WhiteLine} position={[0.09, 0.02, 0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand_3" geometry={nodes.Sand_3.geometry} material={materials.CourtColor} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
          </group>
          <group name="Court" position={[-0.36, 0, -0.16]}>
            <mesh name="Sand6_3" geometry={nodes.Sand6_3.geometry} material={materials.WhiteLine} position={[-0.06, -0.01, 0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand5_3" geometry={nodes.Sand5_3.geometry} material={materials.WhiteLine} position={[0.06, -0.01, -0.13]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand9_3" geometry={nodes.Sand9_3.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand4_3" geometry={nodes.Sand4_3.geometry} material={materials.WhiteLine} position={[0, 0.03, 0]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand3_3" geometry={nodes.Sand3_3.geometry} material={materials.WhiteLine} position={[-0.09, -0.01, -0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand2_3" geometry={nodes.Sand2_3.geometry} material={materials.WhiteLine} position={[0.09, -0.01, 0.04]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand1_3" geometry={nodes.Sand1_3.geometry} material={materials.WhiteLine} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
            <mesh name="Sand7_3" geometry={nodes.Sand7_3.geometry} material={materials.WhiteLine} position={[-0.09, 0.02, -0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand8_3" geometry={nodes.Sand8_3.geometry} material={materials.WhiteLine} position={[0.09, 0.02, 0.04]} rotation={[-Math.PI, -1.13, -Math.PI]} />
            <mesh name="Sand_4" geometry={nodes.Sand_4.geometry} material={materials.CourtColor} position={[0, -0.01, 0]} rotation={[0, -0.44, 0]} />
          </group>
        </group>
        <group name="Cloner" position={[-3.29, 0, -0.57]} rotation={[0, 0.05, 0]}>
          <mesh name="Cube4_0" geometry={nodes.Cube4_0.geometry} material={nodes.Cube4_0.material} position={[0, 0, 0.3]} />
          <mesh name="Cube4_1_1" geometry={nodes.Cube4_1_1.geometry} material={nodes.Cube4_1_1.material} position={[0, 0, 0.27]} />
          <mesh name="Cube4_2" geometry={nodes.Cube4_2.geometry} material={nodes.Cube4_2.material} position={[0, 0, 0.24]} />
          <mesh name="Cube4_3" geometry={nodes.Cube4_3.geometry} material={nodes.Cube4_3.material} position={[0, 0, 0.21]} />
          <mesh name="Cube4_4" geometry={nodes.Cube4_4.geometry} material={nodes.Cube4_4.material} position={[0, 0, 0.18]} />
          <mesh name="Cube4_5" geometry={nodes.Cube4_5.geometry} material={nodes.Cube4_5.material} position={[0, 0, 0.15]} />
          <mesh name="Cube4_6" geometry={nodes.Cube4_6.geometry} material={nodes.Cube4_6.material} position={[0, 0, 0.12]} />
          <mesh name="Cube4_7" geometry={nodes.Cube4_7.geometry} material={nodes.Cube4_7.material} position={[0, 0, 0.09]} />
          <mesh name="Cube4_8" geometry={nodes.Cube4_8.geometry} material={nodes.Cube4_8.material} position={[0, 0, 0.06]} />
          <mesh name="Cube4_9" geometry={nodes.Cube4_9.geometry} material={nodes.Cube4_9.material} position={[0, 0, 0.03]} />
          <mesh name="Cube4_10" geometry={nodes.Cube4_10.geometry} material={nodes.Cube4_10.material} />
          <mesh name="Cube4_11" geometry={nodes.Cube4_11.geometry} material={nodes.Cube4_11.material} position={[0, 0, -0.03]} />
          <mesh name="Cube4_12" geometry={nodes.Cube4_12.geometry} material={nodes.Cube4_12.material} position={[0, 0, -0.06]} />
          <mesh name="Cube4_13" geometry={nodes.Cube4_13.geometry} material={nodes.Cube4_13.material} position={[0, 0, -0.09]} />
          <mesh name="Cube4_14" geometry={nodes.Cube4_14.geometry} material={nodes.Cube4_14.material} position={[0, 0, -0.12]} />
          <mesh name="Cube4_15" geometry={nodes.Cube4_15.geometry} material={nodes.Cube4_15.material} position={[0, 0, -0.15]} />
          <mesh name="Cube4_16" geometry={nodes.Cube4_16.geometry} material={nodes.Cube4_16.material} position={[0, 0, -0.18]} />
          <mesh name="Cube4_17" geometry={nodes.Cube4_17.geometry} material={nodes.Cube4_17.material} position={[0, 0, -0.21]} />
          <mesh name="Cube4_18" geometry={nodes.Cube4_18.geometry} material={nodes.Cube4_18.material} position={[0, 0, -0.24]} />
          <mesh name="Cube4_19" geometry={nodes.Cube4_19.geometry} material={nodes.Cube4_19.material} position={[0, 0, -0.27]} />
          <mesh name="Cube4_20" geometry={nodes.Cube4_20.geometry} material={nodes.Cube4_20.material} position={[0, 0, -0.3]} />
        </group>
        <group name="Cloner1" position={[-2.72, 0, -0.6]} rotation={[Math.PI, -0.05, Math.PI]}>
          <mesh name="Cube4_0_1" geometry={nodes.Cube4_0_1.geometry} material={nodes.Cube4_0_1.material} position={[0, 0, 0.3]} />
          {/* <mesh name="Cube4_1_2" geometry={nodes.Cube4_1_2.geometry} material={nodes.Cube4_1_2.material} position={[0, 0, 0.27]} /> */}
          <mesh name="Cube4_2_1" geometry={nodes.Cube4_2_1.geometry} material={nodes.Cube4_2_1.material} position={[0, 0, 0.24]} />
          <mesh name="Cube4_3_1" geometry={nodes.Cube4_3_1.geometry} material={nodes.Cube4_3_1.material} position={[0, 0, 0.21]} />
          <mesh name="Cube4_4_1" geometry={nodes.Cube4_4_1.geometry} material={nodes.Cube4_4_1.material} position={[0, 0, 0.18]} />
          <mesh name="Cube4_5_1" geometry={nodes.Cube4_5_1.geometry} material={nodes.Cube4_5_1.material} position={[0, 0, 0.15]} />
          <mesh name="Cube4_6_1" geometry={nodes.Cube4_6_1.geometry} material={nodes.Cube4_6_1.material} position={[0, 0, 0.12]} />
          <mesh name="Cube4_7_1" geometry={nodes.Cube4_7_1.geometry} material={nodes.Cube4_7_1.material} position={[0, 0, 0.09]} />
          <mesh name="Cube4_8_1" geometry={nodes.Cube4_8_1.geometry} material={nodes.Cube4_8_1.material} position={[0, 0, 0.06]} />
          <mesh name="Cube4_9_1" geometry={nodes.Cube4_9_1.geometry} material={nodes.Cube4_9_1.material} position={[0, 0, 0.03]} />
          <mesh name="Cube4_10_1" geometry={nodes.Cube4_10_1.geometry} material={nodes.Cube4_10_1.material} />
          <mesh name="Cube4_11_1" geometry={nodes.Cube4_11_1.geometry} material={nodes.Cube4_11_1.material} position={[0, 0, -0.03]} />
          <mesh name="Cube4_12_1" geometry={nodes.Cube4_12_1.geometry} material={nodes.Cube4_12_1.material} position={[0, 0, -0.06]} />
          <mesh name="Cube4_13_1" geometry={nodes.Cube4_13_1.geometry} material={nodes.Cube4_13_1.material} position={[0, 0, -0.09]} />
          <mesh name="Cube4_14_1" geometry={nodes.Cube4_14_1.geometry} material={nodes.Cube4_14_1.material} position={[0, 0, -0.12]} />
          <mesh name="Cube4_15_1" geometry={nodes.Cube4_15_1.geometry} material={nodes.Cube4_15_1.material} position={[0, 0, -0.15]} />
          <mesh name="Cube4_16_1" geometry={nodes.Cube4_16_1.geometry} material={nodes.Cube4_16_1.material} position={[0, 0, -0.18]} />
          <mesh name="Cube4_17_1" geometry={nodes.Cube4_17_1.geometry} material={nodes.Cube4_17_1.material} position={[0, 0, -0.21]} />
          <mesh name="Cube4_18_1" geometry={nodes.Cube4_18_1.geometry} material={nodes.Cube4_18_1.material} position={[0, 0, -0.24]} />
          <mesh name="Cube4_19_1" geometry={nodes.Cube4_19_1.geometry} material={nodes.Cube4_19_1.material} position={[0, 0, -0.27]} />
          <mesh name="Cube4_20_1" geometry={nodes.Cube4_20_1.geometry} material={nodes.Cube4_20_1.material} position={[0, 0, -0.3]} />
        </group>
        <PerspectiveCamera name="Morph" makeDefault={false} far={10000000000} near={0.01} fov={12.84} position={[7.18, 6.2, 9.21]} rotation={[-0.59, 0.6, 0.36]} />
        <PerspectiveCamera name="3" makeDefault={false} far={10000000000} near={0.01} fov={32.27} position={[4.12, 0.26, 1.2]} rotation={[-0.15, 1.24, 0.14]} />
        <PerspectiveCamera name="2" makeDefault={false} far={10000000000} near={0.01} fov={12.84} position={[7.18, 6.2, 9.21]} rotation={[-0.59, 0.6, 0.36]} />
        <PerspectiveCamera name="1" makeDefault={false} far={10000000000} near={0.01} fov={12.84} position={[-2.73, 1.28, 15.07]} rotation={[0.05, -0.26, 0.01]} />
        <mesh name="Water" geometry={nodes.Water.geometry} material={materials.WAter} position={[0, -0.03, 0]} />
        <mesh name="Terrain_remesh" geometry={nodes.Terrain_remesh.geometry} material={materials['Mat.2']} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.61, 0.04, 0.23]} rotation={[0, Math.PI / 9, 0]} />
        <mesh name="Cylinder1" geometry={nodes.Cylinder1.geometry} material={nodes.Cylinder1.material} position={[-0.61, 0.04, 0.87]} rotation={[0, Math.PI / 9, 0]} />
        <mesh name="Sweep" geometry={nodes.Sweep.geometry} material={nodes.Sweep.material} />
        <mesh name="Sweep1" geometry={nodes.Sweep1.geometry} material={nodes.Sweep1.material} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-1.96, 0.04, -0.91]} rotation={[0, 0.23, 0]} />
        <mesh name="Cube1" geometry={nodes.Cube1.geometry} material={nodes.Cube1.material} position={[-1.83, 0.04, -0.88]} rotation={[0, -1.34, 0]} />
        <mesh name="Cube2" geometry={nodes.Cube2.geometry} material={nodes.Cube2.material} position={[-1.31, 0.04, -1.45]} rotation={[Math.PI, -1.28, Math.PI]} />
        <mesh name="Cube6" geometry={nodes.Cube6.geometry} material={nodes.Cube6.material} position={[1.55, 0.04, -0.58]} rotation={[-Math.PI, 0.1, -Math.PI]} />
        <mesh name="Cube3" geometry={nodes.Cube3.geometry} material={nodes.Cube3.material} position={[-0.57, 0, -1.21]} rotation={[0, -0.44, 0]} />
        <mesh name="Sand" geometry={nodes.Sand.geometry} material={materials.Sand} position={[0.04, 0, -0.96]} rotation={[0, -0.44, 0]} />
        <mesh name="Cube4" geometry={nodes.Cube4.geometry} material={nodes.Cube4.material} position={[-2.78, 0.08, -1.11]} rotation={[0, 0.05, 0]} />
        <mesh name="Cube5" geometry={nodes.Cube5.geometry} material={nodes.Cube5.material} position={[-2.33, 0.08, -0.76]} rotation={[0, -1.35, 0]} />
        <mesh name="Cross1" geometry={nodes.Cross1.geometry} material={materials.WhiteLine} position={[-0.65, 0, -1.03]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross2" geometry={nodes.Cross2.geometry} material={materials.WhiteLine} position={[-0.63, 0, -1.08]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross3" geometry={nodes.Cross3.geometry} material={materials.WhiteLine} position={[-0.61, 0, -1.12]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross4" geometry={nodes.Cross4.geometry} material={materials.WhiteLine} position={[-0.59, 0, -1.16]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross5" geometry={nodes.Cross5.geometry} material={materials.WhiteLine} position={[-0.57, 0, -1.21]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross6" geometry={nodes.Cross6.geometry} material={materials.WhiteLine} position={[-0.55, 0, -1.25]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross7" geometry={nodes.Cross7.geometry} material={materials.WhiteLine} position={[-0.53, 0, -1.3]} rotation={[0, 1.14, 0]} />
        <mesh name="Cross" geometry={nodes.Cross.geometry} material={materials.WhiteLine} position={[-0.58, 0, -1.18]} rotation={[0, -0.43, 0]} />
        <mesh name="Cube7" geometry={nodes.Cube7.geometry} material={materials.Wood} position={[-2.01, 0.04, 0.29]} rotation={[0, -0.56, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
